import type { Prisma, User } from "@prisma/client";
import type PgBoss from "pg-boss";
import { db } from "~/database/db.server";
import { sendEmail } from "~/emails/mail.server";
import { ShelfError } from "~/utils/error";
import { Logger } from "~/utils/logger";
import { QueueNames, scheduler } from "~/utils/scheduler.server";
import { assetAlertEmailHtmlString, assetAlertEmailText } from "./emails";
import type { AssetsEventType, AssetsSchedulerData } from "./scheduler.server";
import { createNote } from "../note/service.server";

const ASSET_REMINDER_INCLUDES_FOR_EMAIL = {
  teamMembers: {
    select: {
      user: {
        select: {
          email: true,
          firstName: true,
          lastName: true,
          displayName: true,
        },
      },
    },
  },
  asset: {
    select: {
      id: true,
      title: true,
      mainImage: true,
      mainImageExpiration: true,
    },
  },
  organization: { select: { name: true, customEmailFooter: true } },
} satisfies Prisma.AssetReminderInclude;

type UserToEmail = Pick<
  User,
  "email" | "firstName" | "lastName" | "displayName"
> & {
  isOwner?: boolean;
};

const ASSET_SCHEDULER_EVENT_HANDLERS: Record<
  AssetsEventType,
  (job: PgBoss.Job<AssetsSchedulerData>) => Promise<void>
> = {
  REMINDER: async (job) => {
    const reminder = await db.assetReminder.findFirst({
      // eslint-disable-next-line local-rules/require-org-scope-on-id-queries -- idor-safe: background pg-boss job handler, no request/tenant context; reminderId is system-generated by the scheduler queue, not attacker-supplied
      where: { id: job.data.reminderId },
      include: ASSET_REMINDER_INCLUDES_FOR_EMAIL,
    });

    if (!reminder) {
      Logger.warn(
        new ShelfError({
          cause: null,
          message: "Asset reminder not found for scheduled job. Skipping.",
          additionalData: { ...job.data },
          label: "Asset Scheduler",
          shouldBeCaptured: false,
        })
      );
      return;
    }

    const usersToSendEmail = reminder.teamMembers
      .filter((tm) => !!tm.user)
      .map((teamMember) => teamMember.user! as UserToEmail);

    const hasTeamMemberWithoutUser = reminder.teamMembers.some(
      (tm) => !tm.user
    );

    /**
     * If there is some teamMember without a user associated
     * that means the access has been revoked to that teamMember.
     * Then, in this case we have to send an email to the owner with special note.
     */
    if (hasTeamMemberWithoutUser) {
      const owner = await db.user.findFirst({
        where: {
          userOrganizations: {
            some: {
              organizationId: reminder.organizationId,
              roles: { has: "OWNER" },
            },
          },
        },
        select: {
          email: true,
          firstName: true,
          lastName: true,
          displayName: true,
        },
      });

      if (!owner) {
        throw new ShelfError({
          cause: null,
          message: "No owner found",
          label: "Asset Scheduler",
        });
      }

      usersToSendEmail.push({
        ...owner,
        isOwner: true,
      });
    }

    /** Sending alert mails to all associated users. */
    await Promise.all([
      ...usersToSendEmail.map(async (user) => {
        const html = await assetAlertEmailHtmlString({
          asset: reminder.asset,
          user,
          reminder,
          workspaceName: reminder.organization.name,
          isOwner: user.isOwner,
          customEmailFooter: reminder.organization.customEmailFooter,
        });

        sendEmail({
          subject: "⏰ Asset Reminder Notice - Shelf",
          to: user.email,
          text: assetAlertEmailText({
            asset: reminder.asset,
            user,
            reminder,
            workspaceName: reminder.organization.name,
            isOwner: user.isOwner,
            customEmailFooter: reminder.organization.customEmailFooter,
          }),
          html,
        });
      }),
      createNote({
        assetId: reminder.assetId,
        // why: scope the note's asset to the reminder's org so the
        // scheduled job cannot write a note onto a foreign-tenant asset
        // (defense-in-depth cross-org IDOR guard)
        organizationId: reminder.organizationId,
        userId: reminder.createdById,
        type: "UPDATE",
        content: `**System** has sent **${reminder.name.trim()}** reminder.`,
      }),
    ]);
  },
};

/**
 * This function is used to register asset workers.
 * Workers are used to process scheduled events.
 *
 * On handler failure we log (last-retry only, mirroring the email worker's
 * noise control in `emails/email.worker.server.ts`) and **rethrow** so
 * pg-boss marks the job failed and retries it per the bounded `retryLimit`
 * set on enqueue in `scheduler.server.ts`. Previously the catch swallowed the
 * error and returned, so pg-boss marked the job COMPLETED even on failure —
 * silently losing the reminder with no retry.
 *
 * @throws {ShelfError} Rethrows the wrapped cause after logging, so pg-boss
 * treats the job as failed and retries it.
 */
export async function regierAssetWorkers() {
  await scheduler.work<AssetsSchedulerData>(
    QueueNames.assetsQueue,
    // why: includeMetadata exposes job.retrycount/job.retrylimit on the job
    // object below, which we need to only log on the final retry attempt
    { includeMetadata: true },
    async (job) => {
      const handler = ASSET_SCHEDULER_EVENT_HANDLERS[job.data.eventType];

      try {
        await handler(job);
      } catch (cause) {
        // why: pg-boss increments retrycount at fetch time, so with N retries
        // the handler observes retrycount = 0, 1, 2, ... N — the final attempt
        // has retrycount === retrylimit. Using `- 1` here double-logs (fires on
        // both the second-to-last AND the final attempt).
        const isLastRetry =
          job.retrycount != null &&
          job.retrylimit != null &&
          job.retrycount >= job.retrylimit;

        if (isLastRetry) {
          Logger.error(
            new ShelfError({
              cause,
              message: "Something went wrong while executing scheduled work.",
              additionalData: {
                data: job.data,
                work: job.data.eventType,
                retryCount: job.retrycount,
                retryLimit: job.retrylimit,
              },
              label: "Asset Scheduler",
            })
          );
        }

        throw cause;
      }
    }
  );
}
