#!/usr/bin/env bash
set -euo pipefail

#############################################################################
# Book-by-model E2E fixture seeder
#
# Creates (or tears down) a reproducible RESERVED booking that reserves 2
# units of a dedicated AssetModel, with two concrete units whose QR ids are
# known — the exact state the fulfil-and-check-out flow needs. Writes the
# resulting ids to `.maestro/env/e2e.env` as SHELF_TEST_* vars so the Maestro
# flows can consume them (see flows/bookings/14-*).
#
# WHY THIS EXISTS: the fulfil scanner needs a model whose unit QR ids you
# KNOW so you can scan them. The picker-driven flow 13 can't (it reserves
# whatever model the picker surfaces), so fulfil coverage needs a fixture.
# Before this, the state was hand-seeded with ad-hoc psql every run.
#
# Usage:
#   ./seed-e2e.sh up      # create fixtures, write env/e2e.env
#   ./seed-e2e.sh down     # remove fixtures
#
# Targets the workspace named "$WORKSPACE" (default "GRANULAR WORKSPACE").
# Reads the DB connection from the monorepo-root .env (DIRECT_URL), or from
# $DATABASE_URL if set. QA DB only — never point this at production.
#############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAESTRO_DIR="$(dirname "$SCRIPT_DIR")"
MONO_ROOT="$(cd "$MAESTRO_DIR/../../.." && pwd)"
ENV_OUT="$MAESTRO_DIR/env/e2e.env"
WORKSPACE="${WORKSPACE:-GRANULAR WORKSPACE}"

# Stable ids so `down` is idempotent and re-running `up` is a no-op-then-create.
MODEL_ID="e2e_fulfil_model"
BOOKING_NAME="E2E Fulfil Booking"

DB="${DATABASE_URL:-}"
if [ -z "$DB" ]; then
  DB=$(grep -m1 '^DIRECT_URL=' "$MONO_ROOT/.env" | cut -d= -f2- | tr -d '"'"'"'' | sed 's/?.*//')
fi
if [ -z "$DB" ]; then
  echo "✗ No DB connection. Set DATABASE_URL or add DIRECT_URL to $MONO_ROOT/.env" >&2
  exit 1
fi

psql_q() { psql "$DB" -v ON_ERROR_STOP=1 -tA "$@"; }

ORG_ID=$(psql_q -c "select id from \"Organization\" where name='${WORKSPACE}' limit 1;")
if [ -z "$ORG_ID" ]; then
  echo "✗ Workspace '${WORKSPACE}' not found in this DB." >&2
  exit 1
fi

cmd="${1:-}"
case "$cmd" in
  up)
    # Two available INDIVIDUAL assets in the workspace that carry a QR — these
    # become the model's concrete units. Fails loudly if the workspace lacks
    # two, rather than seeding an untestable fixture.
    read -r ASSET_A ASSET_B <<<"$(psql_q -c "
      select string_agg(id, ' ') from (
        select a.id from \"Asset\" a
        join \"Qr\" q on q.\"assetId\"=a.id
        where a.\"organizationId\"='${ORG_ID}'
          and a.\"assetModelId\" is null
        order by a.\"createdAt\" desc limit 2
      ) t;")"
    if [ -z "${ASSET_A:-}" ] || [ -z "${ASSET_B:-}" ]; then
      echo "✗ Need 2 model-free assets with a QR in '${WORKSPACE}'." >&2
      exit 1
    fi

    OWNER_ID=$(psql_q -c "select \"userId\" from \"UserOrganization\" where \"organizationId\"='${ORG_ID}' and 'OWNER'=any(roles) limit 1;")

    psql "$DB" -v ON_ERROR_STOP=1 >/dev/null <<SQL
BEGIN;
DELETE FROM "BookingModelRequest" r USING "Booking" b
  WHERE r."bookingId"=b.id AND b.name='${BOOKING_NAME}' AND b."organizationId"='${ORG_ID}';
DELETE FROM "Booking" WHERE name='${BOOKING_NAME}' AND "organizationId"='${ORG_ID}';
UPDATE "Asset" SET "assetModelId"=NULL WHERE "assetModelId"='${MODEL_ID}';
DELETE FROM "AssetModel" WHERE id='${MODEL_ID}';

INSERT INTO "AssetModel" (id,name,"organizationId","userId","createdAt","updatedAt")
VALUES ('${MODEL_ID}','E2E Fulfil Model','${ORG_ID}','${OWNER_ID}',NOW(),NOW());
UPDATE "Asset" SET "assetModelId"='${MODEL_ID}' WHERE id IN ('${ASSET_A}','${ASSET_B}');

INSERT INTO "Booking" (id,name,status,"organizationId","creatorId","custodianUserId",
                       "from","to","createdAt","updatedAt")
VALUES ('e2e_fulfil_booking','${BOOKING_NAME}','RESERVED','${ORG_ID}','${OWNER_ID}','${OWNER_ID}',
        NOW()+interval '1 hour', NOW()+interval '1 day', NOW(), NOW());
INSERT INTO "BookingModelRequest" (id,"bookingId","assetModelId",quantity,"createdAt","updatedAt","fulfilledQuantity")
VALUES ('e2e_fulfil_req','e2e_fulfil_booking','${MODEL_ID}',2,NOW(),NOW(),0);
COMMIT;
SQL

    QR_A=$(psql_q -c "select id from \"Qr\" where \"assetId\"='${ASSET_A}' limit 1;")
    QR_B=$(psql_q -c "select id from \"Qr\" where \"assetId\"='${ASSET_B}' limit 1;")
    OUTSIDER=$(psql_q -c "
      select q.id from \"Asset\" a join \"Qr\" q on q.\"assetId\"=a.id
      where a.\"organizationId\"='${ORG_ID}' and a.\"assetModelId\" is null
      order by a.\"createdAt\" asc limit 1;")

    mkdir -p "$MAESTRO_DIR/env"
    cat > "$ENV_OUT" <<ENV
# Generated by seed-e2e.sh — book-by-model fulfil fixture. Do not edit by hand.
SHELF_TEST_MODEL_BOOKING_NAME=${BOOKING_NAME}
SHELF_TEST_MODEL_UNIT_QR_A=${QR_A}
SHELF_TEST_MODEL_UNIT_QR_B=${QR_B}
SHELF_TEST_MODEL_OUTSIDER_QR=${OUTSIDER}
ENV
    echo "✓ Seeded '${BOOKING_NAME}' (RESERVED, 2 units of E2E Fulfil Model) in '${WORKSPACE}'."
    echo "  unit A QR: ${QR_A}   unit B QR: ${QR_B}   outsider QR: ${OUTSIDER}"
    echo "  wrote $ENV_OUT"
    ;;
  down)
    psql "$DB" -v ON_ERROR_STOP=1 >/dev/null <<SQL
BEGIN;
DELETE FROM "BookingModelRequest" WHERE id='e2e_fulfil_req';
DELETE FROM "Booking" WHERE id='e2e_fulfil_booking';
UPDATE "Asset" SET "assetModelId"=NULL WHERE "assetModelId"='${MODEL_ID}';
DELETE FROM "AssetModel" WHERE id='${MODEL_ID}';
COMMIT;
SQL
    rm -f "$ENV_OUT"
    echo "✓ Removed book-by-model fulfil fixture from '${WORKSPACE}'."
    ;;
  *)
    echo "Usage: $0 up|down" >&2
    exit 1
    ;;
esac
